### ISSUE TITLE
Configure log rotation

### ISSUE THREAD

**Issue by micheljung** [FAForever/faf-stack#47]
All containers write endless docker log files. The current python server's log file is 75G large.

Example:
```
version: '3.2'
services:
  nginx:
    image: 'nginx:latest'
    ports:
      - '80:80'
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
```
